# Generated by Django 5.2.4 on 2025-08-08 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0002_arrangement_slug_ensemble_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
