# Generated by Django 5.2.4 on 2025-08-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0004_arrangement_composer_arrangement_default_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='piece_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
