# Generated by Django 5.2.4 on 2025-08-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0007_alter_arrangementversion_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrangement',
            old_name='default_style',
            new_name='style',
        ),
    ]
