# Generated by Django 5.2.4 on 2025-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0017_exportfailurelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementversion',
            name='num_lines_per_page',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
