# Generated by Django 5.2.4 on 2026-03-19 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0027_add_part_name_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_repos', to='ensembles.arrangement')),
            ],
            options={
                'verbose_name': 'Git Repo',
                'verbose_name_plural': 'Git Repos',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=128)),
                ('author_email', models.EmailField(max_length=254)),
                ('authored_at', models.DateTimeField()),
                ('committed_at', models.DateTimeField()),
                ('parent_sha', models.CharField(blank=True, max_length=40, null=True)),
                ('tag', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commits', to=settings.AUTH_USER_MODEL)),
                ('git_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='ensembles.gitrepo')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'ordering': ['-authored_at'],
            },
        ),
    ]
