# Generated by Django 5.2.4 on 2026-03-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0028_commit_arrangementversion_commit_gitrepo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangementversion',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='gitrepo',
            name='arrangement',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
        migrations.DeleteModel(
            name='GitRepo',
        ),
    ]
