# Generated by Django 5.2.4 on 2026-03-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0028_gitrepo_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementversion',
            name='commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrangement_version', to='ensembles.commit'),
        ),
    ]
