# Generated by Django 5.2.4 on 2026-03-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0029_remove_arrangementversion_commit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128)),
                ('commit_message', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='ensembles.arrangement')),
                ('parent_commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ensembles.commit')),
            ],
        ),
    ]
