# Generated by Django 5.2.4 on 2026-03-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0030_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='commit_message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='commit',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit', to='ensembles.arrangementversion'),
        ),
    ]
