# Generated by Django 5.2.4 on 2026-03-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0030_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='commit_message',
            new_name='message',
        ),
    ]
