# Generated by Django 5.2.4 on 2026-04-19 19:29

import ensembles.formatting_steps_constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0033_commit_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementversion',
            name='formatting_steps',
            field=models.JSONField(default=ensembles.formatting_steps_constants.default_formatting_steps),
        ),
    ]
