# Generated by Django 5.2.4 on 2026-04-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0035_arrangementversion_staff_spacing_strategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementversion',
            name='staff_spacing_strategy',
            field=models.CharField(choices=[('predict', 'Predict from score'), ('preserve', 'Keep from uploaded file'), ('override', 'Custom spatium')], default='preserve', max_length=16),
        ),
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name='arrangementversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('arrangement',), name='unique_latest_version_per_arrangement'),
        ),
    ]
