# Generated by Django 5.2.4 on 2026-06-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0037_commit_is_merge_commit_commit_is_merge_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='default_part_book_layout',
            field=models.CharField(choices=[('single_sided', 'Single-sided'), ('double_sided', 'Double-sided')], default='double_sided', max_length=20),
        ),
        migrations.AddField(
            model_name='partbook',
            name='layout',
            field=models.CharField(blank=True, choices=[('single_sided', 'Single-sided'), ('double_sided', 'Double-sided')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partname',
            name='part_book_layout_override',
            field=models.CharField(blank=True, choices=[('single_sided', 'Single-sided'), ('double_sided', 'Double-sided')], max_length=20, null=True),
        ),
    ]
