services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend.Dockerfile
    volumes:
    - ./apps:/app/apps
    - ./packages:/app/packages
    - ./scripts/docker-backend-dev-cmd.sh:/app/scripts/docker-backend-dev-cmd.sh:ro
    ports:
      - "8000:8000"
    command:
      - bash
      - /app/scripts/docker-backend-dev-cmd.sh
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend.Dockerfile
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7

  celery:
    build:
      context: .
      dockerfile: ./apps/backend.Dockerfile
    volumes:
    - ./apps:/app/apps
    - ./packages:/app/packages
    - ./scripts/docker-backend-dev-cmd.sh:/app/scripts/docker-backend-dev-cmd.sh:ro
    command:
      - bash
      - /app/scripts/docker-backend-dev-cmd.sh
      - celery
      - -A
      - backend
      - worker
      - --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    depends_on:
      - backend
      - redis
      - db

  musescore-headless:
    build:
      context: .
      dockerfile: ./apps/musescore-headless/musescore.Dockerfile
    restart: unless-stopped
    environment:
      - QT_QPA_PLATFORM=offscreen
    expose:
    - "1234"
volumes:
  postgres_data:
