# Generated by Django 5.2.4 on 2025-08-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0006_arrangementversion_file_name_arrangementversion_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='arrangementversion',
            unique_together=set(),
        ),
    ]
