# Generated by Django 5.2.4 on 2025-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0010_arrangementversion_num_measures_per_line_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='act_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
