# Generated by Django 5.2.4 on 2025-08-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0011_alter_arrangement_act_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangementversion',
            name='uuid',
        ),
    ]
