# Generated by Django 5.2.4 on 2025-09-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0015_diff_error_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='version',
        ),
        migrations.DeleteModel(
            name='EnsembleSetlistEntry',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
