# Generated by Django 5.2.4 on 2025-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0018_arrangementversion_num_lines_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='mvt_no',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
