# Generated by Django 5.2.4 on 2025-12-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0019_arrangement_mvt_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangement',
            options={'ordering': ['mvt_no']},
        ),
        migrations.AddField(
            model_name='arrangementversion',
            name='audio_state',
            field=models.CharField(choices=[('N', 'None'), ('P', 'Processing'), ('C', 'Complete'), ('E', 'Error')], default='N', max_length=1),
        ),
    ]
