# Generated by Django 5.2.4 on 2025-12-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0021_ensemble_owner_alter_arrangementversion_audio_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
