# Generated by Django 5.2.4 on 2025-12-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0022_ensemble_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensembleusership',
            name='role',
            field=models.CharField(choices=[('M', 'member'), ('A', 'admin')], default='M', max_length=1),
        ),
    ]
