# Generated by Django 5.2.4 on 2026-01-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0024_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['-is_score', 'name']},
        ),
    ]
