# Generated by Django 5.2.4 on 2026-01-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0025_alter_part_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part',
            new_name='PartAsset',
        ),
    ]
