# Generated by Django 5.2.4 on 2026-01-21 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0025_alter_part_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='mvt_no',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='PartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_books', to='ensembles.ensemble')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ensembles.partbook')),
            ],
        ),
        migrations.CreateModel(
            name='PartBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensembles.arrangement')),
                ('arrangement_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensembles.arrangementversion')),
                ('part_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ensembles.partbook')),
            ],
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_names', to='ensembles.ensemble')),
            ],
        ),
        migrations.AddField(
            model_name='partbook',
            name='part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_books', to='ensembles.partname'),
        ),
        migrations.CreateModel(
            name='PartAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=500)),
                ('is_score', models.BooleanField(default=False)),
                ('arrangement_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='ensembles.arrangementversion')),
                ('part_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ensembles.partname')),
            ],
            options={
                'ordering': ['-is_score'],
            },
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.AlterUniqueTogether(
            name='partbook',
            unique_together={('ensemble', 'part_name', 'revision')},
        ),
    ]
