# Generated by Django 5.2.4 on 2026-01-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0026_ensemble_part_books_generating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partname',
            name='slug',
            field=models.SlugField(),
        ),
    ]
