# Generated by Django 5.2.4 on 2026-01-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0026_rename_part_partasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partasset',
            options={'ordering': ['-is_score']},
        ),
        migrations.RemoveField(
            model_name='partasset',
            name='name',
        ),
        migrations.CreateModel(
            name='PartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_books', to='ensembles.ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='PartBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensembles.arrangement')),
                ('arrangement_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensembles.arrangementversion')),
                ('part_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ensembles.partbook')),
            ],
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64)),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_names', to='ensembles.ensemble')),
            ],
        ),
        migrations.AddField(
            model_name='partbook',
            name='part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_books', to='ensembles.partname'),
        ),
        migrations.AddField(
            model_name='partasset',
            name='name_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ensembles.partname'),
        ),
    ]
