# Generated by Django 5.2.4 on 2026-01-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0026_ensemble_part_books_generating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='latest_part_book_revision',
            field=models.IntegerField(default=1),
        ),
    ]
