# Generated by Django 5.2.4 on 2026-01-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0026_ensemble_latest_part_book_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partname',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
