# Generated by Django 5.2.4 on 2026-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0026_ensemble_latest_part_book_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangementversion',
            name='error_on_export',
        ),
        migrations.RemoveField(
            model_name='arrangementversion',
            name='is_processing',
        ),
        migrations.AddField(
            model_name='arrangementversion',
            name='export_state',
            field=models.CharField(choices=[('N', 'none'), ('P', 'processing'), ('C', 'complete'), ('E', 'error')], default='N', max_length=1),
        ),
    ]
