# Generated by Django 5.2.4 on 2026-01-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0026_alter_arrangement_mvt_no_partbook_partbookentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='style',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('broadway', 'Broadway'), ('classical', 'Classical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diff',
            name='error_msg',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='diff',
            name='file_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='default_style',
            field=models.CharField(choices=[('jazz', 'Jazz'), ('broadway', 'Broadway'), ('classical', 'Classical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exportfailurelog',
            name='comments',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exportfailurelog',
            name='error_msg',
            field=models.CharField(max_length=512),
        ),
    ]
