# Generated by Django 5.2.4 on 2026-01-20 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0027_alter_partasset_options_remove_partasset_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partname',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='mvt_no',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='partasset',
            name='name_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ensembles.partname'),
        ),
        migrations.AlterUniqueTogether(
            name='partbook',
            unique_together={('ensemble', 'part_name', 'revision')},
        ),
    ]
