# Generated by Django 5.2.4 on 2026-01-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0027_alter_arrangement_style_alter_diff_error_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangementversion',
            name='file_name',
            field=models.CharField(max_length=128),
        ),
    ]
