# Generated by Django 5.2.4 on 2026-01-29 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembles', '0027_ensemble_latest_part_book_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partbookentry',
            name='part_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ensembles.partasset'),
        ),
    ]
