# Generated by Django 5.2.4 on 2025-07-03 13:31

import divisi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ArrangementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='divisi.arrangement')),
            ],
        ),
        migrations.AddField(
            model_name='arrangement',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='divisi.ensemble'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
                ('filename', models.FileField(upload_to=divisi.models._part_upload_path)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='divisi.arrangement')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensemble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_order', to='divisi.ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreOrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=120)),
                ('score_order_list_id', models.PositiveIntegerField()),
                ('score_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='divisi.scoreorder')),
            ],
            options={
                'ordering': ['score_order_id'],
                'unique_together': {('score_order', 'score_order_id')},
            },
        ),
    ]
