# Generated by Django 5.2.4 on 2025-07-06 03:44

import divisi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('act_number', models.IntegerField(default=1)),
                ('piece_number', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['act_number', 'piece_number'],
            },
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ArrangementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(default='1.0.0', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='divisi.arrangement')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('arrangement', 'version_label')},
            },
        ),
        migrations.AddField(
            model_name='arrangement',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='divisi.ensemble'),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=divisi.models._part_upload_path)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='divisi.arrangementversion')),
            ],
        ),
        migrations.CreateModel(
            name='EnsembleSetlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divisi.arrangement')),
                ('ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist_entries', to='divisi.ensemble')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('ensemble', 'order_index')},
            },
        ),
    ]
