# Generated by Django 5.2.4 on 2025-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='act_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='piece_number',
            field=models.IntegerField(default=1),
        ),
    ]
