# Generated by Django 5.2.4 on 2025-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='file_name',
            field=models.CharField(default='name'),
            preserve_default=False,
        ),
    ]
