# Generated by Django 5.2.4 on 2025-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisi', '0002_arrangement_act_number_arrangement_piece_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
