# Generated by Django 5.2.4 on 2026-01-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisi', '0002_uploadsession_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='file_name',
            field=models.CharField(max_length=128),
        ),
    ]
