# Generated by Django 5.2.3 on 2025-06-26 03:32

import django.utils.timezone
import scores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to=scores.models.score_upload_path)),
                ('version', models.CharField(default='v1.0.0', max_length=6)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded')),
            ],
        ),
    ]
